version: "2.4"
services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper-1
    ports:
      - 12181:2181
    environment:
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/zookeeper.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper-2
    ports:
      - 12182:2181
    environment:
      ZOOKEEPER_SERVER_ID: "2"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/zookeeper.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper-3
    ports:
      - 12183:2181
    environment:
      ZOOKEEPER_SERVER_ID: "3"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/zookeeper.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  kafka-1:
    #image: confluentinc/cp-kafka:7.0.0
    build:
      context: ./
      dockerfile: Dockerfile.kafka
    hostname: kafka-1
    ports:
      - 19092:19092
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_LISTENERS: "INTERNAL://kafka-1:9092,EXTERNAL://:19092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:9092,EXTERNAL://localhost:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_BROKER_ID: "1"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-broker.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_BROKER_RACK: wr
      KAFKA_OFFSETS_REPLICATION_FACTOR: ""
      KAFKA_CONFLUENT_OFFSETS_TOPIC_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count":2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_CONFLUENT_TRANSACTION_STATE_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      #replica.fetch.max.bytes: 52428800
      #              replica.fetch.response.max.bytes: 524288000
      #              replica.socket.receive.buffer.bytes: 8388608
      #              socket.send.buffer.bytes: 2097152
      #              socket.receive.buffer.bytes: 2097152
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 10487600
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 8388608
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 2097152
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 2097152
      KAFKA_METRIC_REPORTS: io.confluent.metrics.reporter.ConfluentMetricsReporter

    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  kafka-2:
    #image: confluentinc/cp-kafka:7.0.0
    build:
      context: ./
      dockerfile: Dockerfile.kafka
    hostname: kafka-2
    ports:
      - 19093:19093
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENERS: "INTERNAL://kafka-2:9092,EXTERNAL://:19093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-2:9092,EXTERNAL://localhost:19093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: "2"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-broker.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_BROKER_RACK: wr
      KAFKA_OFFSETS_REPLICATION_FACTOR: ""
      KAFKA_CONFLUENT_OFFSETS_TOPIC_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count":2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_CONFLUENT_TRANSACTION_STATE_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 10487600
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 8388608
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 2097152
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 2097152
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  kafka-3:
    #image: confluentinc/cp-kafka:7.0.0
    build:
      context: ./
      dockerfile: Dockerfile.kafka
    hostname: kafka-3
    ports:
      - 19094:19094
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENERS: "INTERNAL://kafka-3:9092,EXTERNAL://:19094"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-3:9092,EXTERNAL://localhost:19094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: "3"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-broker.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_BROKER_RACK: wo
      KAFKA_OFFSETS_REPLICATION_FACTOR: ""
      KAFKA_CONFLUENT_OFFSETS_TOPIC_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count":2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_CONFLUENT_TRANSACTION_STATE_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 10487600
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 8388608
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 2097152
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 2097152
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  kafka-4:
    #image: confluentinc/cp-kafka:7.0.0
    build:
      context: ./
      dockerfile: Dockerfile.kafka
    hostname: kafka-4
    ports:
      - 19095:19095
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENERS: "INTERNAL://kafka-4:9092,EXTERNAL://:19095"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-4:9092,EXTERNAL://localhost:19095"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: "4"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-broker.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_BROKER_RACK: er
      KAFKA_OFFSETS_REPLICATION_FACTOR: ""
      KAFKA_CONFLUENT_OFFSETS_TOPIC_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count":2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_CONFLUENT_TRANSACTION_STATE_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 10487600
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 8388608
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 2097152
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 2097152
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/

  kafka-5:
    #image: confluentinc/cp-kafka:7.0.0
    build:
      context: ./
      dockerfile: Dockerfile.kafka
    hostname: kafka-5
    ports:
      - 19096:19096
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENERS: "INTERNAL://kafka-5:9092,EXTERNAL://:19096"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-5:9092,EXTERNAL://localhost:19096"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: "5"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-broker.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_BROKER_RACK: er
      KAFKA_OFFSETS_REPLICATION_FACTOR: ""
      KAFKA_CONFLUENT_OFFSETS_TOPIC_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count":2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_CONFLUENT_TRANSACTION_STATE_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 10487600
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 8388608
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 2097152
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 2097152
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/


  kafka-6:
    #image: confluentinc/cp-kafka:7.0.0
    build:
      context: ./
      dockerfile: Dockerfile.kafka
    hostname: kafka-6
    ports:
      - 19097:19097
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_LISTENERS: "INTERNAL://kafka-6:9092,EXTERNAL://:19097"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-6:9092,EXTERNAL://localhost:19097"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_BROKER_ID: "6"
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-broker.yml
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_BROKER_RACK: eo
      KAFKA_OFFSETS_REPLICATION_FACTOR: ""
      KAFKA_CONFLUENT_OFFSETS_TOPIC_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count":2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_CONFLUENT_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_CONFLUENT_TRANSACTION_STATE_LOG_PLACEMENT_CONSTRAINTS: '{"version": 2,"replicas": [{"count": 2, "constraints": {"rack": "wr"}},{"count": 2, "constraints": {"rack": "er"}}], "observers": [{"count": 1, "constraints":{ "rack":"wo"}},{"count": 1, "constraints":{ "rack":"eo"}}] }'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: 10487600
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 8388608
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 2097152
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 2097152
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/


  producer:
    hostname: producer
    container_name: producer
    build: ./sample-application/producer
    environment:
      JAVA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-producer.yml -Xmx256M -Xms256M"
      KAFKA_BOOTSTRAP_SERVERS: "kafka-1:9092, kafka-2:9092, kafka-3:9092"
      TOPIC: "orders"
      REPLICATION_FACTOR: -1
      NUMBER_OF_PARTITIONS: 4
      MESSAGE_BACKOFF: 10 # Frequency of message injection
      NUMBER_MESSAGE_PER_BATCH: 100
      CATALOG_PRODUCTS_PATH: /usr/share/products
      KAFKA_ACKS: "all"
      KAFKA_LINGER_MS: "25"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
      - ./referential/products:/usr/share/products
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - streams #Stream create topic
      - schema-registry

  streams:
    build: ./sample-application/streams
    hostname: streams-1
    container_name: streams-1
    environment:
      JAVA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=1234:/usr/share/jmx_exporter/kafka-streams-post-2.5.yml -Xmx256M -Xms256M
      KAFKA_BOOTSTRAP_SERVERS: "kafka-1:9092, kafka-2:9092, kafka-3:9092"
      INPUT_TOPIC: "orders"
      APPLICATION_ID: "order-aggregate-streams-v2"
      REPLICATION_FACTOR: -1
      NUMBER_OF_PARTITIONS: 4
      KAFKA_COMMIT_INTERVAL_MS: 100 # 1 seconds
      KAFKA_CACHE_MAX_BYTES_BUFFERING: 0 # 1MB
      KAFKA_COMPRESSION_TYPE: zstd
      KAFKA_METRICS_RECORDING_LEVEL: "DEBUG"
      KAFKA_NUM_STREAM_THREADS: 4
      KAFKA_REPLICATION_FACTOR: -1
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_PRODUCER_ACKS: -1
      KAFKA_PRODUCER_BATCH_SIZE: 800000
      KAFKA_LINGER_MS: 10
      KAFKA_TOPIC_MIN_INSYNC_REPLICAS: 3
      KAFKA_PROCESSING_GUARANTEE: "exactly_once_v2"
      KAFKA_RETRIES: 3000
      KAFKA_MAX_BLOCK_MS: 120000
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    ports:
      - "8080:8080"
    volumes:
    - ./jmx-exporter:/usr/share/jmx_exporter/
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry

  prometheus:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:7.3.3
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-1:9092,kafka-2:9092,kafka-3:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            access-log:
              enabled: false
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    ports:
      - 8082:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
