#!/bin/bash

source ./utils/utils.sh

docker-compose down -v
docker-compose up -d

KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
KAFKA_5_IP=$(container_to_ip kafka-5)
KAFKA_6_IP=$(container_to_ip kafka-6)
ZOO_1_IP=$(container_to_ip zookeeper-1)
ZOO_2_IP=$(container_to_ip zookeeper-2)
ZOO_3_IP=$(container_to_ip zookeeper-3)
interface=eth0

main() {
  add_delay kafka-1 35.0 $KAFKA_4_IP $KAFKA_5_IP $KAFKA_6_IP $ZOO_3_IP
  add_delay kafka-2 35.0 $KAFKA_4_IP $KAFKA_5_IP $KAFKA_6_IP $ZOO_3_IP
  add_delay kafka-3 35.0 $KAFKA_4_IP $KAFKA_5_IP $KAFKA_6_IP $ZOO_3_IP

  add_delay kafka-4 35.0 $KAFKA_1_IP $KAFKA_2_IP $KAFKA_3_IP $ZOO_1_IP $ZOO_2_IP
  add_delay kafka-5 35.0 $KAFKA_1_IP $KAFKA_2_IP $KAFKA_3_IP $ZOO_1_IP $ZOO_2_IP
  add_delay kafka-6 35.0 $KAFKA_1_IP $KAFKA_2_IP $KAFKA_3_IP $ZOO_1_IP $ZOO_2_IP

  sleep 15
  docker-compose exec kafka-1 sh -c "KAFKA_OPTS= && kafka-topics --bootstrap-server kafka-1:9092 --create --topic __consumer_offsets --partitions 50"
  docker-compose exec kafka-1 sh -c "KAFKA_OPTS= && kafka-topics --bootstrap-server kafka-1:9092 --create --topic __transaction_state --partitions 50"

}

main
